# Gains for the Proportional-Derivative Joint Space Controller
# P and D gains for each axis.
joint_space_ctrl:
  #derivative
  gains_d: [ 100, 75, 75, 73, 15, 5 ]
  # gains_d: [ 200, 75, 75, 73, 15, 5 ]

  #proportional
  # gains_p: [ 50, 612.71801, 612.71801, 150, 40, 5 ]
  gains_p: [ 5, 8.1696, 8.1696, 2.0548, 2.6667, 1.0000 ]
  # gains_p: [ 200, 612.71801, 612.71801, 150, 40, 5 ]

  #integral
  # gains_i: [ 0, 0, 0, 0, 0, 0]
  gains_i: [ 1, 1, 1, 1, 1, 1 ]
  # gains_i: [ 5, 5, 5, 5, 5, 5]

  # Desired position in deg [J1, J2, J3, J4, J5, J6], e.g. [90, -45, 30, -70, 40, 40]
  # Home: [0, -90, 0, -90, 0, 0]
  # goal1: [ 0, -75, 75, 0, 90, 0 ]
  # time: 10.0

cartesian_space_ctrl:
  # [x y z, rx, ry, rz]
  #derivative
  gains_d: [ 50, 50, 50,   0, 0, 0 ]
  # gains_d: [ 200, 75, 75, 73, 15, 5 ]

  #proportional
  # gains_p: [ 5, 5, 5,   0, 0, 0 ]
  gains_p: [ 10, 10, 10,   0, 0, 0 ]

  #integral
  gains_i: [ 2, 2, 2, 0, 0, 0 ]
  # gains_i: [ 1, 1, 1, 1, 1, 1]
  # gains_i: [ 5, 5, 5, 5, 5, 5]

  # Desired position in deg [J1, J2, J3, J4, J5, J6], e.g. [90, -45, 30, -70, 40, 40]
  # Home: [0, -90, 0, -90, 0, 0]
  # goal1: [ 0, -90, 90, 0, 90, 0 ]
  # time: 3.0

other_parameter_settings:

  time_total: 2000

  # Desired position in deg [J1, J2, J3, J4, J5, J6], e.g. [90, -45, 30, -70, 40, 40]
  # Home:             [  0, -90,  0, -90,  0,  0 ]
  non_singular_state: [ 180, -90, 90,   0, 90,  0 ]
  time_move_out_sing_state: 5.0

  # in frame 0 coordinate system
  circle_traj:
    center: [ 0.5, 0.0, 0.4 ] # [m]
    radius: [ 0.25, 0.25, 0.0 ] # [m]
    frequency: [ 0.5, 0.5, 0.0 ] # [rad/s]
    phase: [ 0.0, 90.0, 0.0 ] # [DEG]

  # collision avoidance
  link_modifier: 0.7
  radial_influence: 0.5
